import { IntelligenceItem, IntelligenceSnapshot, TimelineEvent } from "@/lib/types";
import { daysBetween } from "@/lib/utils";
const positiveWords=["trailer","elenco","estreia","confirmado","produção","novidade","sucesso","primeira imagem","teaser","audiência","headline","filmad"];
const negativeWords=["polêmica","crítica","atraso","boicote","risco","reclamação","cancelamento","vazamento","controversia","controversy","hate"];
export function classifySentiment(text:string){const t=text.toLowerCase();const pos=positiveWords.filter(w=>t.includes(w)).length;const neg=negativeWords.filter(w=>t.includes(w)).length;return neg>pos?{sentiment:"negative" as const,reason:"O conteúdo contém sinais de risco, crítica, polêmica ou incerteza que podem impactar percepção da série."}:{sentiment:"positive" as const,reason:"O conteúdo indica interesse, novidade, expectativa ou conversa favorável para a franquia."}}
export function enrich(items:IntelligenceItem[]){return dedupe(items).map(i=>{const c=classifySentiment(`${i.title} ${i.summary} ${i.tags.join(" ")}`);const risk=c.sentiment==="negative"?Math.min(95,55+i.riskScore):Math.max(5,i.riskScore-12);const opp=c.sentiment==="positive"?Math.min(98,58+i.opportunityScore):Math.max(12,i.opportunityScore);return {...i,sentiment:c.sentiment,sentimentReason:c.reason,riskScore:risk,opportunityScore:opp}})}
export function dedupe(items:IntelligenceItem[]){const seen=new Set<string>();return items.filter(i=>{const key=(i.title.toLowerCase().replace(/[^a-z0-9áéíóúãõç]/gi,"").slice(0,80));if(seen.has(key))return false;seen.add(key);return true})}
export function buildTimeline(items:IntelligenceItem[]):TimelineEvent[]{const byDate=new Map<string,IntelligenceItem[]>();items.forEach(i=>{const d=i.publishedAt.slice(0,10);byDate.set(d,[...(byDate.get(d)||[]),i])});return [...byDate.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([date,list])=>{const top=list.sort((a,b)=>(b.reach+b.opportunityScore)-(a.reach+a.opportunityScore))[0];const neg=list.filter(i=>i.sentiment==="negative").length;return {date,title:top?.title||"Movimentação detectada",description:`${list.length} sinais monitorados no dia, com ${neg} alertas negativos.`,intensity:Math.min(100,Math.round(list.reduce((s,i)=>s+i.reach,0)/Math.max(1,list.length))),sentiment:neg>list.length/2?"negative":"positive",items:list.map(i=>i.id)}})}
export function buildSnapshot(items:IntelligenceItem[], from:string, to:string):IntelligenceSnapshot{const enriched=enrich(items).sort((a,b)=>+new Date(b.publishedAt)-+new Date(a.publishedAt));const pos=enriched.filter(i=>i.sentiment==="positive").length;const neg=enriched.length-pos;const sources=[...new Set(enriched.map(i=>i.source))].map(source=>({source,count:enriched.filter(i=>i.source===source).length})).sort((a,b)=>b.count-a.count).slice(0,8);const risks=enriched.filter(i=>i.sentiment==="negative").sort((a,b)=>b.riskScore-a.riskScore).slice(0,5).map(i=>`${i.title} — ${i.sentimentReason}`);const opportunities=enriched.sort((a,b)=>b.opportunityScore-a.opportunityScore).slice(0,5).map(i=>`${i.title} — potencial para social, PR ou creators.`);const timeline=buildTimeline(enriched);const dates=daysBetween(from,to);const trends=dates.filter((_,idx)=>idx%7===0||dates.length<40).map((date,idx)=>({date,value:Math.max(5,Math.min(100,Math.round(28+Math.sin(idx/2)*12+enriched.filter(i=>i.publishedAt.slice(0,10)<=date).length*1.8))),topic:"Harry Potter HBO Max"}));return {project:"Lumos",generatedAt:new Date().toISOString(),dateFrom:from,dateTo:to,totalItems:enriched.length,items:enriched,timeline,summary:{headline:`Harry Potter mantém ${pos>=neg?"tração positiva":"atenção com riscos reputacionais"} no Brasil, com ${enriched.length} sinais consolidados entre imprensa, social e plataformas.`,bullets:[`Sentimento: ${pos} positivos e ${neg} negativos.`,`Principais fontes: ${sources.slice(0,3).map(s=>s.source).join(", ") || "monitoramento inicial"}.`,`Maiores oportunidades estão concentradas em nostalgia, casting, bastidores e expectativa de trailer.`,`Riscos pedem atenção contínua em conversas de fandom, comparações com os filmes e possíveis polêmicas de produção.`],risks:risks.length?risks:["Nenhum risco crítico detectado no período analisado."],opportunities:opportunities.length?opportunities:["Criar calendário editorial de nostalgia e educação de universo para aquecer audiência."],sentiment:{positive:pos,negative:neg},topSources:sources},trends,creators:[{name:"Creators de cultura pop BR",platform:"YouTube/TikTok/Instagram",score:91,audience:"Fandom, geek e entretenimento",fit:"Alta afinidade para explicadores, teorias e reacts.",risks:["Briefing precisa evitar spoilers e claims não confirmados."]},{name:"Portais geek",platform:"Web/YouTube",score:86,audience:"Leitores de Omelete, Jovem Nerd e IGN",fit:"Bom para PR, listas e contextualização de franquia.",risks:["Monitorar manchetes sensacionalistas."]}]}}
